kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv
  namespace: rabbitmq
  labels:
    type: local
spec:
  storageClassName: rabbitmq-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data"