kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pvc
  namespace: rabbitmq
spec:
  storageClassName: rabbitmq-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi