---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-sa
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq-01
    app.kubernetes.io/component: rabbitmq-server
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-01-rabbitmq-endpoint-reader
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq-01
    app.kubernetes.io/component: rabbitmq-server
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-01-rabbitmq-endpoint-reader
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq-01
    app.kubernetes.io/component: rabbitmq-server
subjects:
- kind: ServiceAccount
  name: rabbitmq-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-01-rabbitmq-endpoint-reader